### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by rozzzly** [virtualthoughts/slickedit-select#1]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (C:\Users\Administrator\AppData\Local\atom\app-0.188.0\resources\app\src\atom.js:54:11)
Object.activate (C:\Users\Administrator\.atom\packages\slickedit-select\lib\slickedit-select.coffee:9:20)
```

**Comment by virtualthoughts** [comment]
Fixed a while ago... just cleaning up issue
